<a href="https://colab.research.google.com/github/AnitaKirkovska/MachineLearning_HW1/blob/master/Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Load the training and test data using Keras (No validation set)**

In [12]:
from keras.datasets import mnist

(train_images_original, train_labels_original), (test_images_original, test_labels_original) = mnist.load_data()

Using TensorFlow backend.


## **Preparing the data**

In [13]:
train_images = train_images_original.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
train_images.shape


(60000, 784)

In [14]:
test_images = test_images_original.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255
test_images.shape

(10000, 784)

**This is an array of the train labels for which I need to use the categorical function, and create a matrix out of 1 and 0 where 1 will define the index for the number that I am looking for. Ex: {1,0,0,0...} means it is 1.**

In [17]:
train_labels_original

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

# **Using the to_categorical() function **

In [0]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels_original)
test_labels = to_categorical(test_labels_original)

In [71]:
train_labels.shape

(60000, 10)

# **Mini-batch stochastic gradient descent**

A few training examples are selected to compute the gradient


In [69]:
m = train_images.shape[0] 
m


60000

In [0]:
# add x0 = 1 to each instance
train_images_new = np.c_[np.ones((m, 1)), train_images]

# create array with x1=0 
theta = np.array([[0], [2]])
# add x0 = 1 to each instance
theta_new = np.c_[np.ones((2, 1)), theta]

In [45]:
train_images_new

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [46]:
theta_new

array([[1., 0.],
       [1., 2.]])

In [0]:
epoch = 10

In [0]:
alpha = 0.01

In [53]:
np.random.seed(42)
initial_weight = np.random.randn(2, 1)
initial_weight

array([[ 0.49671415],
       [-0.1382643 ]])

In [66]:
weight = initial_weight
weight_path_mgd = []
batch_size = 10


weight_path_mgd.append(weight)
for epoch in range(epoch):
    shuffled_indices = np.random.permutation(m)
    train_images_new_shuffled = train_images_new[shuffled_indices]
    y_shuffled = train_labels[shuffled_indices]
    
    for i in range(0, m, batch_size):
        xi = train_images_new_shuffled[i:i+batch_size]
        yi = y_shuffled[i:i+batch_size]
        gradient = 2/batch_size * xi.T.dot(xi.dot(weight) - yi)
        weight = weight - alpha * gradient
        weight_path_mgd.append(weight)

ValueError: ignored