<a href="https://colab.research.google.com/github/AnitaKirkovska/MachineLearning_HW1/blob/master/Problem1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.special

The Network architecture

In [0]:
class neuralArch:
  
  def __init__ (self, inputnodes, outputnodes, learningrate):
    self.inodes = inputnodes
    self.onodes = outputnodes
    
    #link weight natrices. wio -> input and hidden, who -> hidden and output
    self.wio = (numpy.random.rand(self.inodes, self.onodes) - 0.5)
    
    #learning rate
    self.lr = learningrate
    
    #activation function -> sigmoid
    self.activation_function = lambda x: scipy.special.expit(x)
    
    pass
  
  def train(self, inputs_list, targets_list):
    
    #convert to 2d array
    inputs = numpy.array(inputs_list, ndmin=2).T
    targets = numpy.array(targets_list, ndmin=2).T
    
    #calculating signals into last layer 
    last_inputs = numpy.dot(self.wio,inputs)
    last_outputs = self.activation_function(last_inputs)
    
    #output layer error (target - last_outputs)
    last_errors = targets - last_outputs
    
    #hidden layer error
    last_errors = numpy.dot(self.wio.T, last_errors)
    
    #update the weight links between input and last layers
    self.wio += self.lr * numpy.dot((last_errors * last_outputs * (1.0 - last_outputs)), numpy.transpose(inputs))
    
    pass
  
  def query(self,inputs_list):
    
    #convert to 2d array
    inputs = numpy.array(inputs_list, ndmin=2).T
    
    #calculating signals into and from last layer 
    last_inputs = numpy.dot(self.wio,inputs)
    last_outputs = self.activation_function(last_inputs)
    
    return last_outputs

Loading the data

In [0]:
from keras.datasets import mnist

(x_train_org, y_train_org), (x_test_org, y_test_org) = mnist.load_data()

In [109]:
x_train_org.shape

(60000, 28, 28)

In [110]:
y_train_org

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

Preparing the data (Range 1-0)

In [121]:
x_train = x_train_org.reshape((60000, 28 * 28))
scaled_input_x = numpy.asfarray(x_train)/255.0
scaled_input_x


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Target matrix - the labels y

In [0]:
from keras.utils import to_categorical

y_train_org = to_categorical(y_train_org)
y_test_org = to_categorical(y_test_org)

In [113]:
len(y_train_org[0])

10

In [119]:
y_train_org

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

Nodes, learning rate and instance of the network architecture

In [0]:
#output nodes are 10, the # of classifiers we have
input_nodes = len(scaled_input_x[0])
output_nodes = len(y_train_org[0])

learning_rate = 0.3

#instance of the Network
n = neuralArch(input_nodes, output_nodes, learning_rate)

Training the network

In [123]:
epochs = 6


total_lenght = x_number_inputs * y_number_labels

for e in range(epochs):
  n.train(scaled_input_x, y_train_org)
  pass

  

ValueError: ignored